FROM golang:latest as build

WORKDIR /app

RUN go mod init main

COPY ./main.go ./main.go

RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM scratch

COPY --from=build /app/main /bin/main

CMD ["/bin/main"]